name = "pydantic-errors-redirect"
main = "src/index.ts"
compatibility_date = "2023-04-24"
account_id = "58c2606138e6f7346345b5a882718168"
route = "errors.pydantic.dev/*"

[vars]
GITHUB_SHA = "unknown"
